---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine-docker:v1.2.0
stages:
  build:
    workDir: ~/cli-engine-example
    steps:
      - type: checkout
      - type: cache-restore
        key: cli-engine-example{{checksum "package.json"}}
      - run: yarn
      - run: jest
      - run: ./bin/run cli:test
      - type: deploy
        shell: /bin/bash
        command: |
          set -ex
          TAG=`git describe --exact-match HEAD || echo NOTAG`
          if [ "${TAG}" != "NOTAG" ]; then
            yarn run release stable
          fi
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            yarn run release beta
          fi
      - type: cache-save
        key: cli-engine-example{{checksum "package.json"}}
        paths:
          - /usr/local/share/.cache/yarn
          - ~/cli-engine-example/node_modules
