---
version: 2
jobs:
  build:
    working_directory: /tmp/cli-engine-example
    docker:
      - image: dickeyxxx/cli-engine-docker:v1.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cli-engine-example-{{ .Branch }}-{{checksum "package.json"}}
            - cli-engine-example-{{ .Branch }}
            - cli-engine-example-master
      - run: yarn
      - run: jest
      - run: ./bin/run cli:test
      - deploy:
          command: |
            set -ex
            TAG=`git describe --exact-match HEAD || echo NOTAG`
            if [ "${TAG}" != "NOTAG" ]; then
              cli-release stable
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cli-release beta
            fi
      - save_cache:
          key: cli-engine-example-{{ .Branch}}-{{checksum "package.json"}}
          paths:
            - /tmp/cli-engine-example/node_modules
            - /usr/local/share/.cache/yarn
      - save_cache:
          key: cli-engine-example-{{ .Branch}}
          paths:
            - /usr/local/share/.cache/yarn

